"""P3.2 — Substack/newsletter draft generator (unit + integration).

Turns the weekly digest (weekly-<date>.md) and the weekly interview questions
(weekly-questions-<date>.md) into ONE human-reviewable newsletter draft. The
draft is explicitly marked DRAFT / review-required — this is an assistant, not
an autopilot; a human edits and presses send.

Depends on P2.2 dedup only indirectly: the weekly digest it consumes is already
deduped/ranked, so the draft inherits non-repetitive, credibility-ordered
stories. Tests build the input .md files in a temp dir (no LLM, no network).
"""
from __future__ import annotations

import datetime as _dt
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from phantom_ai_feed import newsletter as _nl  # noqa: E402


WEEKLY_MD = """# phantom-ai-feed weekly digest — week ending 2026-06-13

_Generated by phantom_ai_feed.weekly (phantom-exec); 12 items from 8/8 feeds._

1. **Llama 3 405B open weights** — Meta ships the largest open model yet.
2. **vLLM PagedAttention v2** — 40% less KV-cache memory.

## 本週趨勢
開源模型持續逼近閉源 SOTA。
"""

QUESTIONS_MD = """# phantom-ai-feed weekly interview questions — week ending 2026-06-13

_Stub generator: questions templated from this week's top sources._

1. Explain Transformers and one production failure mode.
2. Design an offline benchmark for RAG.
3. If Agents regressed 15%, what is your debugging tree?
"""


def _write_inputs(tmp_path: Path, date="2026-06-13"):
    log_dir = tmp_path
    (log_dir / f"weekly-{date}.md").write_text(WEEKLY_MD, encoding="utf-8")
    (log_dir / f"weekly-questions-{date}.md").write_text(
        QUESTIONS_MD, encoding="utf-8"
    )
    return log_dir


# --------------------------------------------------------------------------- #
# pure assembly                                                               #
# --------------------------------------------------------------------------- #
def test_build_draft_includes_digest_and_questions():
    draft = _nl.build_draft(
        _dt.date(2026, 6, 13), WEEKLY_MD, QUESTIONS_MD
    )
    # the ranked stories survive
    assert "Llama 3 405B open weights" in draft
    assert "vLLM PagedAttention v2" in draft
    # the interview questions are included as a learning section
    assert "Explain Transformers" in draft
    assert "debugging tree" in draft


def test_build_draft_marks_review_required():
    draft = _nl.build_draft(_dt.date(2026, 6, 13), WEEKLY_MD, QUESTIONS_MD)
    low = draft.lower()
    assert "draft" in low
    assert "review" in low  # explicit human-review banner


def test_build_draft_has_newsletter_structure():
    draft = _nl.build_draft(_dt.date(2026, 6, 13), WEEKLY_MD, QUESTIONS_MD)
    # a title, an intro, the stories, a questions section, a footer
    assert draft.startswith("#")
    assert "2026-06-13" in draft
    # the weekly trend commentary is carried into the draft body
    assert "本週趨勢" in draft or "開源模型" in draft
    # a self-test/learning section heading for the questions
    assert "## " in draft  # at least one section heading


def test_build_draft_strips_generator_meta_lines():
    """The internal '_Generated by ..._' / '_Stub generator ..._' provenance
    lines must NOT leak into a reader-facing newsletter draft."""
    draft = _nl.build_draft(_dt.date(2026, 6, 13), WEEKLY_MD, QUESTIONS_MD)
    assert "_Generated by phantom_ai_feed" not in draft
    assert "Stub generator: questions templated" not in draft


def test_build_draft_handles_missing_questions():
    draft = _nl.build_draft(_dt.date(2026, 6, 13), WEEKLY_MD, "")
    assert "Llama 3 405B" in draft
    # graceful note rather than a crash / empty section
    assert "draft" in draft.lower()


# --------------------------------------------------------------------------- #
# integration: read files, write draft                                        #
# --------------------------------------------------------------------------- #
def test_run_reads_weekly_and_questions_writes_draft(tmp_path):
    log_dir = _write_inputs(tmp_path)
    out = _nl.run(log_dir=log_dir, end=_dt.date(2026, 6, 13))
    assert out.exists()
    assert out.name == "newsletter-draft-2026-06-13.md"
    body = out.read_text(encoding="utf-8")
    assert "Llama 3 405B open weights" in body
    assert "Explain Transformers" in body
    assert "draft" in body.lower() and "review" in body.lower()


def test_run_missing_weekly_raises(tmp_path):
    # only questions present, no weekly digest → explicit error, not silent empty
    (tmp_path / "weekly-questions-2026-06-13.md").write_text(
        QUESTIONS_MD, encoding="utf-8"
    )
    try:
        _nl.run(log_dir=tmp_path, end=_dt.date(2026, 6, 13))
    except SystemExit as e:
        assert "weekly" in str(e).lower()
    else:
        raise AssertionError("expected SystemExit when weekly digest is missing")


def test_run_idempotent_unless_force(tmp_path):
    log_dir = _write_inputs(tmp_path)
    out1 = _nl.run(log_dir=log_dir, end=_dt.date(2026, 6, 13))
    mtime1 = out1.stat().st_mtime_ns
    # second run without force → skip (idempotent)
    out2 = _nl.run(log_dir=log_dir, end=_dt.date(2026, 6, 13))
    assert out2 == out1
    assert out2.stat().st_mtime_ns == mtime1
    # with force → rewritten
    out3 = _nl.run(log_dir=log_dir, end=_dt.date(2026, 6, 13), force=True)
    assert out3 == out1


def test_cli_smoke(tmp_path):
    import subprocess

    log_dir = _write_inputs(tmp_path)
    proc = subprocess.run(
        [sys.executable, "-m", "phantom_ai_feed.newsletter",
         "--log-dir", str(log_dir), "--end", "2026-06-13"],
        capture_output=True, text=True, encoding="utf-8",
        cwd=str(Path(__file__).resolve().parent.parent),
    )
    assert proc.returncode == 0, proc.stderr
    assert (log_dir / "newsletter-draft-2026-06-13.md").exists()
