"""Daily digest orchestrator.

Pipeline:
  load feeds.toml → fetch_all → summarize per entry → render Markdown
  → write ~/.phantom-mesh/logs/phantom-ai-feed/<date>.md
  → (best-effort) `phantom event capture` per entry into FTS5

CLI:
  python -m phantom_ai_feed.digest                 # uses GEMINI_API_KEY
  python -m phantom_ai_feed.digest --use-stub      # no API call
  python -m phantom_ai_feed.digest --out /tmp/foo  # override out dir
"""
from __future__ import annotations

import argparse
import datetime as _dt
import sys
from pathlib import Path

from . import capture as _capture
from . import fetch as _fetch
from . import summarize as _sum

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_FEEDS = REPO_ROOT / "sources" / "feeds.toml"
DEFAULT_OUT = Path.home() / ".phantom-mesh" / "logs" / "phantom-ai-feed"


def _status_counts(
    sections: list[tuple[dict, list[dict] | str]]
) -> tuple[int, int, int, int]:
    """Return (ok, empty, error, total) across the rendered sections.

    - ok:    parsed with >=1 entry
    - empty: parsed but produced 0 entries
    - error: fetch/parse raised (carried as an error string)
    """
    ok = empty = error = 0
    for _feed, payload in sections:
        if isinstance(payload, str):
            error += 1
        elif payload:
            ok += 1
        else:
            empty += 1
    return ok, empty, error, len(sections)


def _render(date: _dt.date, sections: list[tuple[dict, list[dict] | str]], *, stub: bool) -> str:
    badge = "stub-summarizer" if stub else "gemini-flash"
    ok, empty, error, total = _status_counts(sections)
    lines = [
        f"# phantom-ai-feed digest — {date.isoformat()}",
        "",
        f"_Generated by phantom_ai_feed.digest ({badge})._",
        "",
        f"**Feeds: {ok}/{total} feeds OK** "
        f"({ok} ok · {empty} empty · {error} error)",
        "",
    ]
    for feed, payload in sections:
        lines.append(
            f"## {feed['name']}  _(category: {feed.get('category', 'misc')})_"
        )
        lines.append(f"<{feed.get('url','')}>")
        lines.append("")
        if isinstance(payload, str):
            lines.append(f"> ERROR: {payload}")
            lines.append("")
            continue
        if not payload:
            lines.append("_(no entries parsed)_")
            lines.append("")
            continue
        for e in payload:
            title = e.get("title") or "(untitled)"
            link = e.get("link") or ""
            lines.append(f"- **[{title}]({link})**")
            if e.get("summary"):
                lines.append(f"  - {e['summary']}")
        lines.append("")
    return "\n".join(lines)


def _try_capture_fts5(entry: dict) -> "_capture.CaptureResult":
    """Best-effort: append entry to phantom FTS5 via the capture adapter.

    Delegates to ``phantom_ai_feed.capture`` (unit-tested 3-branch CLI seam).
    Never raises — a missing binary or a capture failure is returned as a
    ``CaptureResult`` and otherwise ignored, so a daily run still writes its
    Markdown even when phantom is unavailable.
    """
    return _capture.capture_entry(entry)


def run(
    feeds_toml: Path = DEFAULT_FEEDS,
    out_dir: Path = DEFAULT_OUT,
    *,
    use_stub: bool = False,
    top_n: int = 3,
    force: bool = False,
) -> Path:
    feeds = _fetch.load_feeds(feeds_toml)
    if not feeds:
        raise SystemExit(f"no [[feed]] entries in {feeds_toml}")

    today = _dt.date.today()
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{today.isoformat()}.md"
    if out_path.exists() and not force:
        print(f"already wrote {out_path} — skipping (idempotent)")
        return out_path

    raw = _fetch.fetch_all(feeds, top_n=top_n)
    sections: list[tuple[dict, list[dict] | str]] = []
    for feed, payload in raw:
        if isinstance(payload, Exception):
            sections.append((feed, f"{type(payload).__name__}: {payload}"))
            continue
        enriched: list[dict] = []
        for entry in payload:
            entry["summary"] = _sum.summarize(
                entry.get("summary_excerpt", "") or entry.get("title", ""),
                use_stub=use_stub,
            )
            _try_capture_fts5(entry)
            enriched.append(entry)
        sections.append((feed, enriched))

    out_path.write_text(_render(today, sections, stub=use_stub), encoding="utf-8")
    ok, empty, error, total = _status_counts(sections)
    print(
        f"wrote {out_path} ({ok}/{total} feeds OK; "
        f"{empty} empty, {error} error)"
    )
    return out_path


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="phantom-ai-feed daily digest")
    ap.add_argument("--feeds", type=Path, default=DEFAULT_FEEDS)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--use-stub", action="store_true",
                    help="skip Gemini, use stdlib extractive summary")
    ap.add_argument("--top-n", type=int, default=3)
    ap.add_argument("--force", action="store_true",
                    help="overwrite today's digest if present")
    args = ap.parse_args(argv)
    run(
        feeds_toml=args.feeds,
        out_dir=args.out,
        use_stub=args.use_stub,
        top_n=args.top_n,
        force=args.force,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
