"""Daily digest orchestrator.

Pipeline:
  load feeds.toml → fetch_all → summarize per entry → render Markdown
  → write ~/.phantom-mesh/logs/phantom-ai-feed/<date>.md
  → (best-effort) `phantom event capture` per entry into FTS5

CLI:
  python -m phantom_ai_feed.digest                 # uses GEMINI_API_KEY
  python -m phantom_ai_feed.digest --use-stub      # no API call
  python -m phantom_ai_feed.digest --out /tmp/foo  # override out dir
"""
from __future__ import annotations

import argparse
import datetime as _dt
import shutil
import subprocess
import sys
from pathlib import Path

from . import fetch as _fetch
from . import summarize as _sum

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_FEEDS = REPO_ROOT / "sources" / "feeds.toml"
DEFAULT_OUT = Path.home() / ".phantom-mesh" / "logs" / "phantom-ai-feed"


def _render(date: _dt.date, sections: list[tuple[dict, list[dict] | str]], *, stub: bool) -> str:
    badge = "stub-summarizer" if stub else "gemini-flash"
    lines = [
        f"# phantom-ai-feed digest — {date.isoformat()}",
        "",
        f"_Generated by phantom_ai_feed.digest ({badge})._",
        "",
    ]
    for feed, payload in sections:
        lines.append(
            f"## {feed['name']}  _(category: {feed.get('category', 'misc')})_"
        )
        lines.append(f"<{feed.get('url','')}>")
        lines.append("")
        if isinstance(payload, str):
            lines.append(f"> ERROR: {payload}")
            lines.append("")
            continue
        if not payload:
            lines.append("_(no entries parsed)_")
            lines.append("")
            continue
        for e in payload:
            title = e.get("title") or "(untitled)"
            link = e.get("link") or ""
            lines.append(f"- **[{title}]({link})**")
            if e.get("summary"):
                lines.append(f"  - {e['summary']}")
        lines.append("")
    return "\n".join(lines)


def _try_capture_fts5(entry: dict) -> None:
    """Best-effort: append entry to phantom FTS5 via CLI. Silent on failure."""
    if not shutil.which("phantom"):
        return
    try:
        subprocess.run(
            [
                "phantom", "event", "capture",
                "--kind", "ai-feed",
                "--source", entry.get("source", "phantom-ai-feed"),
                "--title", entry.get("title", "")[:200],
                "--body", entry.get("summary", "")[:2000],
                "--link", entry.get("link", ""),
            ],
            timeout=5,
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.SubprocessError):
        pass


def run(
    feeds_toml: Path = DEFAULT_FEEDS,
    out_dir: Path = DEFAULT_OUT,
    *,
    use_stub: bool = False,
    top_n: int = 3,
    force: bool = False,
) -> Path:
    feeds = _fetch.load_feeds(feeds_toml)
    if not feeds:
        raise SystemExit(f"no [[feed]] entries in {feeds_toml}")

    today = _dt.date.today()
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{today.isoformat()}.md"
    if out_path.exists() and not force:
        print(f"already wrote {out_path} — skipping (idempotent)")
        return out_path

    raw = _fetch.fetch_all(feeds, top_n=top_n)
    sections: list[tuple[dict, list[dict] | str]] = []
    for feed, payload in raw:
        if isinstance(payload, Exception):
            sections.append((feed, f"{type(payload).__name__}: {payload}"))
            continue
        enriched: list[dict] = []
        for entry in payload:
            entry["summary"] = _sum.summarize(
                entry.get("summary_excerpt", "") or entry.get("title", ""),
                use_stub=use_stub,
            )
            _try_capture_fts5(entry)
            enriched.append(entry)
        sections.append((feed, enriched))

    out_path.write_text(_render(today, sections, stub=use_stub), encoding="utf-8")
    ok = sum(1 for _, p in sections if isinstance(p, list))
    print(f"wrote {out_path} ({ok}/{len(feeds)} feeds OK)")
    return out_path


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="phantom-ai-feed daily digest")
    ap.add_argument("--feeds", type=Path, default=DEFAULT_FEEDS)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--use-stub", action="store_true",
                    help="skip Gemini, use stdlib extractive summary")
    ap.add_argument("--top-n", type=int, default=3)
    ap.add_argument("--force", action="store_true",
                    help="overwrite today's digest if present")
    args = ap.parse_args(argv)
    run(
        feeds_toml=args.feeds,
        out_dir=args.out,
        use_stub=args.use_stub,
        top_n=args.top_n,
        force=args.force,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
