"""Substack / newsletter DRAFT generator.

Composes the week's two existing artifacts —

  - ``weekly-<date>.md``           (the ranked, deduped digest from weekly.py)
  - ``weekly-questions-<date>.md`` (the interview questions from
    interview_questions.py)

— into ONE human-reviewable newsletter draft, ``newsletter-draft-<date>.md``.

This is deliberately NOT an autopilot: the output is marked DRAFT and carries a
prominent "human review required before sending" banner. The pipeline's job is
to do the assembly grunt-work (pull the ranked stories, attach a self-test
question section, strip internal provenance lines that shouldn't face readers);
a human edits the voice and presses send.

It depends on P2.2/P2.3 only indirectly: because the weekly digest it consumes
is already cross-source deduped and credibility-ranked, the draft inherits a
non-repetitive, most-important-first story order for free.

Pure stdlib, no network, no LLM — it transforms local Markdown into local
Markdown.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import re
import sys
from pathlib import Path

DEFAULT_LOG_DIR = Path.home() / ".phantom-mesh" / "logs" / "phantom-ai-feed"

# Internal provenance / meta lines we must NOT leak into a reader-facing draft.
# Matches the italic '_Generated by ..._' and '_Stub generator ..._' lines the
# weekly / questions writers emit, plus any other leading-italic meta line.
_META_LINE = re.compile(r"^\s*_.*_\s*$")
# A top-level '# ...' title line from a source doc (we write our own title).
_H1 = re.compile(r"^#\s+")

REVIEW_BANNER = (
    "> **DRAFT — human review required before sending.** This newsletter was "
    "auto-assembled by phantom-ai-feed from this week's digest and interview "
    "questions. Edit the voice, verify every link and claim, then publish."
)


def _strip_meta_and_title(md: str) -> str:
    """Drop the source doc's own H1 title and italic provenance/meta lines,
    keeping the substantive body. Leading/trailing blank lines collapsed."""
    kept: list[str] = []
    for raw in (md or "").splitlines():
        line = raw.rstrip()
        if _H1.match(line):
            continue
        if _META_LINE.match(line):
            continue
        kept.append(line)
    # collapse 3+ blank lines to a single blank
    body = "\n".join(kept).strip("\n")
    return re.sub(r"\n{3,}", "\n\n", body)


def build_draft(
    date: _dt.date, weekly_md: str, questions_md: str
) -> str:
    """Assemble the newsletter draft from the two source Markdown blobs.

    Pure — no I/O. ``questions_md`` may be empty (the section is then a
    graceful note rather than an empty heading).
    """
    iso = date.isoformat()
    stories = _strip_meta_and_title(weekly_md)
    questions = _strip_meta_and_title(questions_md)

    parts: list[str] = [
        f"# AI 前線週報 — week ending {iso}",
        "",
        REVIEW_BANNER,
        "",
        "## 本週重點 / This Week in AI",
        "",
        "歡迎回到 AI 前線週報。以下是本週最重要的 AI 工程進展"
        "（已跨來源去重並依可信度排序）：",
        "",
        stories if stories else "_(no ranked stories this week)_",
        "",
        "## 自我檢測 / Test Yourself",
        "",
    ]
    if questions:
        parts += [
            "用本週的進展檢驗自己——以下面試題可作為學習驗證：",
            "",
            questions,
        ]
    else:
        parts.append("_(no interview questions generated for this week)_")

    parts += [
        "",
        "---",
        "",
        "_由 phantom-ai-feed 自動彙整，發送前需人工審閱。"
        "Assembled locally by phantom-ai-feed; nothing was exfiltrated._",
        "",
    ]
    return "\n".join(parts)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def run(
    log_dir: Path = DEFAULT_LOG_DIR,
    end: _dt.date | None = None,
    *,
    force: bool = False,
) -> Path:
    """Read this week's weekly + questions Markdown and write a newsletter draft.

    Raises ``SystemExit`` if the weekly digest is missing (it is the required
    backbone); a missing questions file degrades to a graceful note. Idempotent
    unless ``force`` (won't clobber an existing draft).
    """
    end = end or _dt.date.today()
    iso = end.isoformat()
    weekly_path = log_dir / f"weekly-{iso}.md"
    questions_path = log_dir / f"weekly-questions-{iso}.md"

    if not weekly_path.exists():
        raise SystemExit(
            f"weekly digest not found: {weekly_path} "
            f"(run `python -m phantom_ai_feed.weekly` first)"
        )

    log_dir.mkdir(parents=True, exist_ok=True)
    out_path = log_dir / f"newsletter-draft-{iso}.md"
    if out_path.exists() and not force:
        print(f"already wrote {out_path} — skipping (idempotent)")
        return out_path

    weekly_md = _read(weekly_path)
    questions_md = _read(questions_path) if questions_path.exists() else ""
    out_path.write_text(build_draft(end, weekly_md, questions_md), encoding="utf-8")
    print(f"wrote {out_path}")
    return out_path


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Assemble a human-reviewable newsletter DRAFT from the "
        "week's digest + interview questions."
    )
    ap.add_argument("--log-dir", type=Path, default=DEFAULT_LOG_DIR)
    ap.add_argument("--end", type=str, default=None,
                    help="YYYY-MM-DD; defaults to today")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing draft for this week")
    args = ap.parse_args(argv)
    end = _dt.date.fromisoformat(args.end) if args.end else None
    run(log_dir=args.log_dir, end=end, force=args.force)
    return 0


if __name__ == "__main__":
    sys.exit(main())
